flowchart TB
subgraph site_A["Site A"]
    subgraph cluster_1_Operator["MongoDB Operator<br/>Management Cluster"]
        MongoOp["MongoDB Kubernetes Operator"]
        MongoOps["MongoDB OpsManager"]
    end
    subgraph cluster_2_Site_AD_DB["Domain Cluster"]
        Site_AD_RS["MongoDB ReplicaSet<br/>Member 1"]
    end
end
subgraph site_B["Site B"]
    subgraph cluster_3_Site_BD_DB["Domain Cluster"]
        Site_BD_RS["MongoDB ReplicaSet<br/>Member 2"]
    end
end
subgraph site_C["Site C"]
    subgraph cluster_4_Site_CD_DB["Domain Cluster"]
        Site_CD_RS["MongoDB ReplicaSet<br/>Member 3"]
    end
end
    subgraph cluster_5_Apps["Application Layer"]
        RC_Site_A["Rocket.Chat<br/>app-cluster-a"]
        RC_Site_B["Rocket.Chat<br/>app-cluster-b"]
        RC_Site_C["Rocket.Chat<br/>app-cluster-c"]
    end
    MongoOp -.Manages.-> Site_AD_RS
    MongoOp -.Manages.-> Site_BD_RS
    MongoOp -.Manages.-> Site_CD_RS
    Site_AD_RS <-.Replication.-> Site_BD_RS
    Site_AD_RS <-.Replication.-> Site_CD_RS
    Site_BD_RS <-.Replication.-> Site_CD_RS
    RC_Site_A --> Site_AD_RS
    RC_Site_B --> Site_BD_RS
    RC_Site_C --> Site_CD_RS
